### PR TITLE
Fix #820: Use configured provider instead of "BC"

### LINKED ISSUE #820: Use configured provider instead of "BC"
### Affected product(s) and version(s)

develop

### Environment

_No response_

### Steps to reproduce, current result, expected result

Instead of using "BC" in parameters, use the constant provided in the library.

### Log output

_No response_

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

File: powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/v4/ml/MlDsa.java [hunk 1]
```diff
@@ -58,7 +59,7 @@ public MlDsa(MLDSAParameterSpec dsaParameterSpec) throws GenericCryptoException
     @Override
     public KeyPair generateKeyPair() throws CryptoProviderException {
         try {
-            final KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("MLDSA", "BC");
+            final KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("MLDSA", PowerAuthConfiguration.CRYPTO_PROVIDER_NAME);
```
Comment (banterCZ) [inline powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/v4/ml/MlDsa.java:62]: Isn't the value also `BC`?

Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/v4/ml/MlDsa.java:62]: Yes it is.

Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/v4/ml/MlDsa.java:62]: The point is to avoid the same "BC" string in the codebase.

**Review by jnpsk — APPROVED** [review]
