### PR TITLE
Fix #828: Update authentication code calculation and verification

### LINKED ISSUE #828: Update authentication code calculation and verification
### Task specification

Use the following algorithm:

## Algorithm

```java
/**
 * Compute the authentication code components for given data using provided factor keys and current counter.
 * @param data - data to be signed
 * @param factorKeys - array of symmetric keys used for authentication code
 * @param CTR_DATA - hash based counter
 */
List<byte[]> computeAuthenticationCodeComponents(byte[] data, List<SecretKey> factorKeys, byte[] CTR_DATA) {
    // ... compute authentication code components
    String LABEL = "PA4CODE";
    List<byte[]> authCodeComponents = new ArrayList<byte[]>();
    for (int i = 1; i <= factorKeys.size(); i++) {
        byte[] KEY_DERIVED_BYTES = null;
        for (int j = 1; j <= i; j++) {
            byte[] INTERMEDIATE_DATA = ByteUtils.concat(CTR_DATA, KEY_DERIVED_BYTES);
            KEY_DERIVED_BYTES = Mac.kmac256(factorKeys.get(j - 1), INTERMEDIATE_DATA, LABEL);
        }
        // ... compute MAC
        SecretKey KEY_DERIVED = KeyConversion.secretKeyFromBytes(KEY_DERIVED_BYTES);
        byte[] AUTH_CODE_COMPONENT = Mac.kmac256(KEY_DERIVED, data, LABEL);
        // ... keep it in the list
        authCodeComponents.add(AUTH_CODE_COMPONENT);
    }
    return authCodeComponents;
}

/**
 * Compute the authentication code for HTTP request purposes for given data using provided keys and current counter.
 * @param data - data to be signed
 * @param factorKeys - array of symmetric keys used for authentication code
 * @param CTR_DATA - hash based counter
 */
String computeOnlineAuthenticationCode(byte[] data, List<SecretKey> factorKeys, byte[] CTR_DATA) {
    // ... at first, calculate authentication code components
    List<byte[]> authCodeBinaryComponents = computeAuthenticationCodeComponents(data, factorKeys, CTR_DATA);  
      
    // ... now convert components into one Base64 string
    byte[] authCodeBytes = new byte[factorKeys.size() * 32];
    for (int i = 0; i < authCodeBinaryComponents.size(); i++) {
        byte[] AUTH_CODE_COMPONENT = authCodeBinaryComponents.get(i);
        // ... append component bytes to final authentication code bytes
        ByteUtils.copy(AUTH_CODE_COMPONENT, 0, authCodeBytes, i * 32, 32);
    }
    // ... final conversion to Base64
    return Base64.encode(authCodeBytes);
}

/**
 * Compute the offline authentication code for given data using provided keys and current counter.
 * @param data - data to be signed
 * @param factorKeys - array of symmetric keys used for authentication code
 * @param CTR_DATA - hash based counter
 * @param componentLength - Length of authentication code component. Value should not be less than 4 or greater than 8.
 */
String computeOfflineAuthenticationCode(byte[] data, List<SecretKey> factorKeys, byte[] CTR_DATA, int componentLength) {
    // Validate length of authentication code component
    if (componentLength < 4 || componentLength > 8) {
        throw new IllegalArgumentException("componentLength is out of allowed range");
    }
    // calculate authentication code components
    List<byte[]> authCodeBinaryComponents = computeAuthenticationCodeComponents(data, factorKeys, CTR_DATA);
	
    // ... compute authentication code components
	String[] authCodeComponents = new String[factorKeys.size()];
    for (int i = 0; i < authCodeComponents.size(); i++) {
        byte[] AUTH_CODE_COMPONENT = authCodeBinaryComponents.get(i);
        // ... decimalize the authentication code component
        int decimalized = (ByteUtils.getInt(ByteUtils.truncate(AUTH_CODE_COMPONENT, 4)) & 0x7FFFFFFF) % Math.pow(10,8);
        authCodeComponents[i] = String.format("%0" + componentLength + "d", decimalized);
	}
    // ... join the decimalized components using "-" character.
    return String.join("-", authCodeComponents);
}
```  

### Hash based counter

```java
byte[] CTR_DATA_next = Hash.sha3_256(CTR_DATA);
```

#### 1F component

```
DERIVED_KEY =  KMAC(key: FACTOR_KEYS[0], 
                    data: CTR_DATA)
                    
MAC = KMAC(key: DERIVED_KEY, data: DATA)
```
    
#### 2F component

```
DERIVED_KEY = KMAC(key: FACTOR_KEYS[1],
                   data: CTR_DATA || 
                         KMAC(key: FACTOR_KEYS[0],
                              data: CTR_DATA))
                                 
MAC = KMAC(key: DERIVED_KEY, data: DATA)
```
    
#### 3F component

```
DERIVED_KEY = KMAC(key: FACTOR_KEYS[2], 
                   data: CTR_DATA ||
                         KMAC(key: FACTOR_KEYS[1],
                              data: CTR_DATA || 
                                    KMAC(key: FACTOR_KEYS[0],
                                         data: CTR_DATA)))
MAC = KMAC(key: DERIVED_KEY, data: DATA)    
```

### PR DESCRIPTION
**Pull request by romanstrobl**
Updated algorithm for authentication code calculation with improved performance.

### CODE REVIEW

File: powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/AuthenticationCodeUtils.java [hunk 1]
```diff
@@ -173,15 +178,14 @@ private List<byte[]> computeAuthCodeComponents(byte[] data, List<SecretKey> fact
...
-                keyDerived = Kmac.kmac256(keyDerivedCurrent, keyDerived, KMAC_AUTH_CODE_CUSTOM_BYTES);
+        for (int i = 1; i <= factorKeys.size(); i++) {
+            byte[] derivedKeyBytes = null;
+            for (int j = 1; j <= i; j++) {
+                final byte[] intermediateData = ByteUtils.concat(ctrData, derivedKeyBytes);
+                derivedKeyBytes = Kmac.kmac256(factorKeys.get(j - 1), intermediateData, KMAC_AUTH_CODE_CUSTOM_BYTES);
             }
-            final byte[] component = Kmac.kmac256(keyDerived, data, KMAC_AUTH_CODE_CUSTOM_BYTES, PowerAuthConfiguration.AUTH_CODE_BINARY_LENGTH_V4);
+            final SecretKey derivedKey = KEY_CONVERTOR.convertBytesToSharedSecretKey(derivedKeyBytes);
+            final byte[] component = Kmac.kmac256(derivedKey, data, KMAC_AUTH_CODE_CUSTOM_BYTES, PowerAuthConfiguration.AUTH_CODE_BINARY_LENGTH_V4);
```
Comment (jnpsk) [inline powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/AuthenticationCodeUtils.java]: Is the conversion to `SecretKey` necessary? Looks like the `kmac` just converts it to bytes anyway as the first step.

**Review by jnpsk — APPROVED** [review]
looks good

File: powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/AuthenticationCodeUtils.java (hunk 1 above)
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/AuthenticationCodeUtils.java]: Good point, I will remove it.

**Comment by romanstrobl** [comment]
Let's wait with merging this pull request until the mobile SDK applies the same change.
