### PR TITLE
Fix #799: ByteUtils.subarray should accept 0 length

### LINKED ISSUE #799: ByteUtils.subarray should accept 0 length
### Affected product(s) and version(s)

develop

### Environment

local

### Steps to reproduce, current result, expected result

Currently the method ByteUtils.subarray() does not accept zero length. This can be a valid use case, so it should just return an empty array.

### Log output

_No response_

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

File: powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/ByteUtils.java [hunk 1]
```diff
@@ -138,9 +138,12 @@ public static byte[] subarray(byte[] array, int start, int length) {
         if (start < 0) {
             throw new IllegalArgumentException("Invalid start index");
         }
-        if (length <= 0) {
+        if (length < 0) {
             throw new IllegalArgumentException("Invalid length");
         }
+        if (length == 0) {
+            return new byte[0];
+        }
```
Comment (jnpsk) [inline powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/ByteUtils.java]: Since the zero-length check runs before validating array bounds, the method accepts calls like `ByteUtils.subarray(new byte[]{1, 2, 3}, 50, 0)`.
I’d either move that explicit check after the index validation or remove it entirely and let `System#arraycopy` handle the zero-length case too.

Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/ByteUtils.java]: Good point, I will move it after.

**Review by jnpsk — APPROVED** [review]
looks ok
